name: "Terraform Proxmox Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    
    # Globalne zmienne dla całego joba – dzięki temu provider je widzi
    env:
      TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
      TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_API_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform Manually
        run: |
          TERRAFORM_VERSION="1.9.8"
          curl -fsSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform.zip
          unzip -o terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
